---
- hosts: all
  become: yes
  tasks:
  - name: Install packages
    apt:
      name:
      - vim
      - git
      state: latest
      cache_valid_time: 3600

  - name: vimrc config
    shell: "git clone https://github.com/benmaia/Ansible_-_Docker.git"

  - name: run script
    shell: "cd Ansible_-_Docker/ansible_packages && bash install.sh"
